export interface CmsField { key:string; label:string; type?:'text'|'textarea'|'number'|'checkbox'|'date'|'select'; options?:string[]; required?:boolean; }
export interface CmsModule { slug:string; label:string; table:string; titleKey:string; statusKey?:string; fields:CmsField[]; specialistHref?:string; }
export const CMS_MODULES:CmsModule[]=[
  {slug:'pages',label:'Website Pages',table:'lx_pages',titleKey:'title',statusKey:'published',fields:[{key:'title',label:'Page title',required:true},{key:'slug',label:'URL slug',required:true},{key:'eyebrow',label:'Eyebrow'},{key:'lead',label:'Lead',type:'textarea'},{key:'seo_title',label:'SEO title'},{key:'meta_description',label:'Meta description',type:'textarea'},{key:'published',label:'Published',type:'checkbox'}]},
  {slug:'categories',label:'Categories',table:'lx_categories',titleKey:'name',statusKey:'published',fields:[{key:'name',label:'Name',required:true},{key:'slug',label:'Slug',required:true},{key:'kind',label:'Type',type:'select',options:['blog','product','media']},{key:'description',label:'Description',type:'textarea'},{key:'sort_order',label:'Sort order',type:'number'},{key:'published',label:'Published',type:'checkbox'}]},
  {slug:'inquiries',label:'Site Inspections',table:'lx_site_inspections',titleKey:'name',statusKey:'status',fields:[{key:'name',label:'Client name',required:true},{key:'phone',label:'Phone',required:true},{key:'email',label:'Email'},{key:'location',label:'Location'},{key:'space_slug',label:'Space',type:'select',options:['bathrooms','kitchens','staircases','floors']},{key:'preferred_date',label:'Preferred date',type:'date'},{key:'preferred_time',label:'Preferred time'},{key:'notes',label:'Client notes',type:'textarea'},{key:'status',label:'Status',type:'select',options:['new','contacted','scheduled','completed','cancelled']},{key:'assigned_to',label:'Assigned to'},{key:'internal_notes',label:'Internal notes',type:'textarea'}]},
  {slug:'media',label:'Media Library',table:'lx_media',titleKey:'name',fields:[{key:'name',label:'Name',required:true},{key:'public_url',label:'Public URL',required:true},{key:'storage_path',label:'Storage path',required:true},{key:'alt_text',label:'Alt text'},{key:'category',label:'Category'}]},
  {slug:'settings',label:'Global Settings',table:'lx_settings',titleKey:'business_name',fields:[{key:'business_name',label:'Business name'},{key:'whatsapp_number',label:'WhatsApp number'},{key:'public_email',label:'Public email'},{key:'business_address',label:'Business address',type:'textarea'},{key:'inspection_fee_lkr',label:'Inspection fee LKR',type:'number'},{key:'warranty_label',label:'Warranty label'},{key:'cloudinary_cloud_name',label:'Cloudinary cloud name'},{key:'integration_notes',label:'HubSpot / Make.com notes',type:'textarea'},{key:'default_seo_title',label:'Default SEO title'},{key:'default_meta_description',label:'Default meta description',type:'textarea'}]},
];
