export interface CmsField { key:string; label:string; type?:'text'|'textarea'|'number'|'checkbox'|'date'|'select'|'datalist'|'image'|'images'|'lines'|'relation'; options?:string[]; required?:boolean; relation?:'spaces'|'designs'; }
export interface CmsChild { label:string; table:string; foreignKey:string; titleKey:string; fields:CmsField[]; }
export interface CmsModule { slug:string; label:string; table:string; titleKey:string; statusKey?:string; fields:CmsField[]; children?:CmsChild[]; }

const designChildren:CmsChild[]=[
  {label:'Size-based public pricing',table:'lx_design_price_tiers',foreignKey:'design_id',titleKey:'label',fields:[
    {key:'label',label:'Fit label',required:true},
    {key:'sqm',label:'Floor area (m²)',type:'number',required:true},
    {key:'new_price_lkr',label:'New bathroom price (LKR)',type:'number',required:true},
    {key:'renovation_price_lkr',label:'Renovation price (LKR)',type:'number',required:true},
    {key:'sort_order',label:'Display order',type:'number'},
  ]},
  {label:'Internal pricing (admin only)',table:'lx_design_internal_pricing',foreignKey:'design_id',titleKey:'additional_cost_per_sqm_lkr',fields:[{key:'additional_cost_per_sqm_lkr',label:'Additional cost per m² (LKR) — hidden from website',type:'number',required:true},{key:'sort_order',label:'Display order',type:'number'}]},
  {label:'Drawings & renders',table:'lx_design_drawings',foreignKey:'design_id',titleKey:'kind',fields:[{key:'kind',label:'Slot',type:'select',options:['render_1','render_2','render_3','render_4','civil','supply_water','waste_drainage','electrical']},{key:'image_url',label:'Image',type:'image',required:true},{key:'caption',label:'Walk-in caption (renders only, e.g. “The vanity wall”)'},{key:'sort_order',label:'Display order',type:'number'}]},
  {label:'Fixtures & finishes',table:'lx_design_fixtures',foreignKey:'design_id',titleKey:'name',fields:[
    {key:'category',label:'Category',type:'datalist',required:true},
    {key:'name',label:'Fixture / finish name',required:true},
    {key:'brand',label:'Brand'},
    {key:'model_code',label:'Model / item code'},
    {key:'finish',label:'Colour / finish'},
    {key:'quantity',label:'Quantity',type:'number',required:true},
    {key:'spec',label:'Specification',type:'textarea'},
    {key:'warranty_period',label:'Product warranty'},
    {key:'reference_price_label',label:'Reference price (e.g. "LKR 96,000" or "LKR 58,000 / m²")'},
    {key:'notes',label:'Selection notes',type:'textarea'},
    {key:'image_url',label:'Fixture image',type:'image'},
    {key:'image_alt',label:'Image description'},
    {key:'included',label:'Included in starting specification',type:'checkbox'},
    {key:'sort_order',label:'Display order',type:'number'},
  ]},
  {label:'Materials & finishes',table:'lx_design_materials',foreignKey:'design_id',titleKey:'brand',fields:[{key:'category',label:'Category',required:true},{key:'brand',label:'Brand / material name',required:true},{key:'item',label:'Item'},{key:'usage_label',label:'Where it is used (e.g. “Wall & floor”, “Vanity”)'},{key:'image_url',label:'Material photo',type:'image'},{key:'sort_order',label:'Sort order',type:'number'}]},
  {label:'Workflow timeline',table:'lx_design_timeline',foreignKey:'design_id',titleKey:'title',fields:[{key:'week_label',label:'Week',required:true},{key:'title',label:'Title',required:true},{key:'description',label:'Description',type:'textarea'},{key:'sort_order',label:'Sort order',type:'number'}]},
  {label:'Questions & answers',table:'lx_design_faq',foreignKey:'design_id',titleKey:'question',fields:[{key:'question',label:'Question',required:true},{key:'answer',label:'Answer',type:'textarea',required:true},{key:'sort_order',label:'Sort order',type:'number'}]},
];
const projectChildren:CmsChild[]=[
  {label:'Gallery',table:'lx_project_gallery',foreignKey:'project_id',titleKey:'image_url',fields:[{key:'image_url',label:'Photo',type:'image',required:true},{key:'sort_order',label:'Sort order',type:'number'}]},
  {label:'Journey',table:'lx_project_journey',foreignKey:'project_id',titleKey:'stage',fields:[{key:'stage',label:'Stage',required:true},{key:'date_label',label:'When'},{key:'note',label:'Note',type:'textarea'},{key:'issue',label:'Issue found',type:'textarea'},{key:'fix',label:'How it was fixed',type:'textarea'},{key:'image_urls',label:'Diary photos',type:'images'},{key:'sort_order',label:'Sort order',type:'number'}]},
  {label:'Project crew',table:'lx_project_crew',foreignKey:'project_id',titleKey:'name',fields:[{key:'name',label:'Name',required:true},{key:'role',label:'Role'},{key:'photo_url',label:'Photo',type:'image'},{key:'tilershub_verified',label:'TILERSHUB verified',type:'checkbox'},{key:'sort_order',label:'Sort order',type:'number'}]},
];

export const CMS_MODULES:CmsModule[]=[
  {slug:'designs',label:'Designs',table:'lx_designs',titleKey:'name',statusKey:'published',fields:[{key:'name',label:'Design name',required:true},{key:'slug',label:'URL slug',required:true},{key:'space_id',label:'Space',type:'relation',relation:'spaces',required:true},{key:'collection',label:'Collection',type:'select',options:['standard','premium','signature']},{key:'tagline',label:'Tagline'},{key:'description',label:'Description',type:'textarea'},{key:'starting_price_lkr',label:'Card price / lowest starting price LKR',type:'number',required:true},{key:'new_starting_price_lkr',label:'New bathroom starting price LKR',type:'number'},{key:'renovation_starting_price_lkr',label:'Renovation starting price LKR',type:'number'},{key:'min_sqm',label:'Minimum m²',type:'number'},{key:'cover_image_url',label:'Cover / doorway image',type:'image'},{key:'inspiration_image_url',label:'Flower image (the name behind the design)',type:'image'},{key:'name_heading',label:'Name section heading (e.g. “Inspired by the Manel flower.”)'},{key:'name_story',label:'Name story',type:'textarea'},{key:'plan_image_url',label:'Floor plan image — optional, replaces the drawn plan',type:'image'},{key:'room_length_m',label:'Minimum-fit room length (m)',type:'number'},{key:'room_width_m',label:'Minimum-fit room width (m)',type:'number'},{key:'video_3d_url',label:'3D walkthrough YouTube URL'},{key:'video_work_url',label:'Built-work YouTube URL'},{key:'workflow_text',label:'Workflow introduction',type:'textarea'},{key:'highlights',label:'Card highlights',type:'lines'},{key:'featured',label:'Featured',type:'checkbox'},{key:'published',label:'Published — complete decision file only',type:'checkbox'},{key:'sort_order',label:'Sort order',type:'number'}],children:designChildren},
  {slug:'projects',label:'Projects',table:'lx_projects',titleKey:'title',statusKey:'published',fields:[{key:'title',label:'Project title',required:true},{key:'slug',label:'URL slug',required:true},{key:'project_ref',label:'Project reference'},{key:'location',label:'Location'},{key:'area_label',label:'Area / room'},{key:'design_id',label:'Design used',type:'relation',relation:'designs'},{key:'duration_label',label:'Duration'},{key:'completed_label',label:'Completed'},{key:'story',label:'Family story',type:'textarea'},{key:'client_requirements',label:'Client requirements — what the family asked for',type:'textarea'},{key:'estimate_label',label:'Estimate / fixed quotation label (e.g. "LKR 2.37M fixed quotation")'},{key:'before_image_url',label:'Before photo',type:'image'},{key:'after_image_url',label:'After photo',type:'image'},{key:'video_url',label:'Project video URL'},{key:'episode_1_url',label:'Episode 01 URL'},{key:'episode_2_url',label:'Episode 02 URL'},{key:'rating',label:'Rating 1–5',type:'number'},{key:'review_text',label:'Review',type:'textarea'},{key:'review_by',label:'Review by'},{key:'review_screenshot_url',label:'Google review screenshot',type:'image'},{key:'featured',label:'Featured',type:'checkbox'},{key:'published',label:'Published',type:'checkbox'}],children:projectChildren},
  {slug:'blog',label:'Blog Articles',table:'blog_posts',titleKey:'title',statusKey:'status',fields:[{key:'title',label:'Title',required:true},{key:'slug',label:'URL slug',required:true},{key:'author',label:'Author'},{key:'category',label:'Category'},{key:'reading_time',label:'Reading time'},{key:'pub_date',label:'Publish date',type:'date'},{key:'cover_image',label:'Cover image',type:'image'},{key:'excerpt',label:'Excerpt',type:'textarea'},{key:'content',label:'Article content',type:'textarea'},{key:'status',label:'Status',type:'select',options:['draft','published']},{key:'meta_title',label:'SEO title'},{key:'meta_description',label:'Meta description',type:'textarea'},{key:'og_image',label:'Social share image',type:'image'},{key:'include_in_sitemap',label:'Include in sitemap',type:'checkbox'}]},
  {slug:'pages',label:'Website Pages',table:'lx_pages',titleKey:'title',statusKey:'published',fields:[{key:'title',label:'Page title',required:true},{key:'slug',label:'URL slug',required:true},{key:'eyebrow',label:'Eyebrow'},{key:'lead',label:'Lead',type:'textarea'},{key:'seo_title',label:'SEO title'},{key:'meta_description',label:'Meta description',type:'textarea'},{key:'published',label:'Published',type:'checkbox'}]},
  {slug:'products',label:'Products',table:'lx_products',titleKey:'name',statusKey:'published',fields:[{key:'name',label:'Name',required:true},{key:'slug',label:'Slug',required:true},{key:'sku',label:'SKU'},{key:'brand',label:'Brand'},{key:'category',label:'Category'},{key:'short_description',label:'Card description',type:'textarea'},{key:'description',label:'Full description',type:'textarea'},{key:'price_lkr',label:'Price LKR',type:'number',required:true},{key:'compare_at_price_lkr',label:'Compare-at price',type:'number'},{key:'display_price',label:'Display price'},{key:'cover_image_url',label:'Cover image',type:'image'},{key:'gallery_image_urls',label:'Gallery photos',type:'images'},{key:'features',label:'Features',type:'lines'},{key:'specifications',label:'Specifications',type:'textarea'},{key:'compatibility_notes',label:'Compatibility notes',type:'textarea'},{key:'stock_status',label:'Stock',type:'select',options:['in_stock','made_to_order','out_of_stock']},{key:'preorder',label:'Pre-order',type:'checkbox'},{key:'featured',label:'Featured',type:'checkbox'},{key:'published',label:'Published',type:'checkbox'},{key:'sort_order',label:'Sort order',type:'number'},{key:'meta_title',label:'SEO title'},{key:'meta_description',label:'Meta description',type:'textarea'}]},
  {slug:'categories',label:'Categories',table:'lx_categories',titleKey:'name',statusKey:'published',fields:[{key:'name',label:'Name',required:true},{key:'slug',label:'Slug',required:true},{key:'kind',label:'Type',type:'select',options:['blog','product','media']},{key:'description',label:'Description',type:'textarea'},{key:'sort_order',label:'Sort order',type:'number'},{key:'published',label:'Published',type:'checkbox'}]},
  {slug:'inspections',label:'Site Inspections',table:'lx_site_inspections',titleKey:'name',statusKey:'status',fields:[{key:'name',label:'Client name',required:true},{key:'phone',label:'Phone',required:true},{key:'email',label:'Email'},{key:'location',label:'Location'},{key:'space_slug',label:'Space',type:'select',options:['bathrooms','kitchens','staircases','floors']},{key:'preferred_date',label:'Preferred date',type:'date'},{key:'preferred_time',label:'Preferred time'},{key:'notes',label:'Client notes',type:'textarea'},{key:'status',label:'Status',type:'select',options:['new','contacted','scheduled','completed','cancelled']},{key:'assigned_to',label:'Assigned to'},{key:'internal_notes',label:'Internal notes',type:'textarea'}]},
  {slug:'team',label:'Team',table:'lx_team_members',titleKey:'name',statusKey:'published',fields:[{key:'name',label:'Name',required:true},{key:'role',label:'Role'},{key:'bio',label:'Bio',type:'textarea'},{key:'photo_url',label:'Photo',type:'image'},{key:'permanent',label:'Permanent team',type:'checkbox'},{key:'tilershub_verified',label:'TILERSHUB verified',type:'checkbox'},{key:'published',label:'Published',type:'checkbox'},{key:'sort_order',label:'Sort order',type:'number'}]},
  {slug:'media',label:'Media Library',table:'lx_media',titleKey:'name',fields:[{key:'name',label:'Name',required:true},{key:'public_url',label:'Public URL',required:true},{key:'storage_path',label:'Storage path',required:true},{key:'alt_text',label:'Alt text'},{key:'category',label:'Category'}]},
  {slug:'settings',label:'Global Settings',table:'lx_settings',titleKey:'business_name',fields:[{key:'business_name',label:'Business name'},{key:'whatsapp_number',label:'WhatsApp number'},{key:'public_email',label:'Public email'},{key:'business_address',label:'Business address',type:'textarea'},{key:'inspection_fee_lkr',label:'Inspection fee LKR',type:'number'},{key:'warranty_label',label:'Warranty label'},{key:'cloudinary_cloud_name',label:'Cloudinary cloud name'},{key:'integration_notes',label:'HubSpot / Make.com notes',type:'textarea'},{key:'default_seo_title',label:'Default SEO title'},{key:'default_meta_description',label:'Meta description',type:'textarea'}]},
];
