export interface PublicInfoPage {
  slug: string; eyebrow: string; title: string; lead: string;
  cards: Array<{ title: string; copy: string }>;
}

export const PUBLIC_INFO_PAGES: PublicInfoPage[] = [
  { slug:'how-it-works', eyebrow:'From first message to handover', title:'A clear process. A fully resolved result.', lead:'Every stage is documented, approved and communicated before the next begins.', cards:[{title:'1 · Discover',copy:'Choose a space or named design and share your location, dimensions and goals.'},{title:'2 · Inspect & customise',copy:'We inspect the site, resolve technical requirements and customise the design file.'},{title:'3 · Quote & approve',copy:'You receive a documented scope, fixed quotation and programme for approval.'},{title:'4 · Build & update',copy:'Verified teams build while progress is shared through WhatsApp.'},{title:'5 · Test & hand over',copy:'We inspect, test, clean and document the completed space and warranty.'}] },
  { slug:'bathroom-renovation', eyebrow:'Bathrooms', title:'Bathroom design & renovation.', lead:'A complete room—designed, documented and built from waterproofing to final fixture.', cards:[{title:'Choose a named design',copy:'Start with a documented Standard, Premium or Signature bathroom.'},{title:'Customised for the room',copy:'Layouts, drawings, finishes and fixtures are adapted to the actual site.'},{title:'One accountable team',copy:'Civil, plumbing, electrical, tiling, ceiling and finishing are coordinated together.'}] },
  { slug:'kitchen-design-build', eyebrow:'Kitchens', title:'Kitchen design & build.', lead:'Storage, workflow, surfaces and services resolved as one complete kitchen.', cards:[{title:'Designed around habits',copy:'We plan cooking, storage, cleaning and movement around the household.'},{title:'Specified completely',copy:'Cabinetry, countertop, sink, tap, fittings, lighting and finishes are documented.'},{title:'Built with coordination',copy:'Trades and suppliers work from one approved design file.'}] },
  { slug:'staircase-design-build', eyebrow:'Staircases', title:'Staircase design & build.', lead:'Structure, step, landing, light and handrail designed as one architectural journey.', cards:[{title:'Measured precisely',copy:'Rise, going, landings and existing structure are checked before design approval.'},{title:'Every edge resolved',copy:'Treads, nosing, cladding, railing, lighting and transitions are specified.'},{title:'Built safely',copy:'Critical dimensions and connections are quality checked during construction.'}] },
  { slug:'floor-design-installation', eyebrow:'Floors', title:'Floor design & installation.', lead:'A complete floor system—from substrate preparation to the final transition.', cards:[{title:'Design direction',copy:'Choose a Sri Lankan landscape design and material character.'},{title:'System specification',copy:'Preparation, waterproofing, adhesive, layout, joints, skirting and trims are resolved.'},{title:'Precision installation',copy:'Levels, alignment and finishing are checked throughout the installation.'}] },
  { slug:'materials-brands', eyebrow:'Materials & brands', title:'Named materials. Documented choices.', lead:'We specify brands and construction systems openly so clients know what is going into their home.', cards:[{title:'Construction systems',copy:'Swisstek adhesive and grout, S-lon pipes, Tokyo Super 2K waterproofing and ACL wiring.'},{title:'Fixtures & finishes',copy:'Swiss Bathware, Rocell, iPanel, tempered glass, Eco Board and 5mm mirrors.'},{title:'Approved alternatives',copy:'Any substitution is documented and approved before purchase or installation.'}] },
  { slug:'pricing-guide', eyebrow:'Pricing clarity', title:'Understand the investment before construction.', lead:'Catalogue prices are honest starting points. The fixed project price follows inspection and customisation.', cards:[{title:'What affects price',copy:'Room size, site condition, selected design, fixture level, access and location.'},{title:'What a quotation includes',copy:'Scope, quantities, materials, fixtures, labour, programme, payment stages and exclusions.'},{title:'What changes later',copy:'Only documented, client-approved variations can change the fixed quotation.'}] },
  { slug:'warranty-aftercare', eyebrow:'Warranty & aftercare', title:'Our responsibility continues after handover.', lead:'Every completed LUXEhome project includes a documented one-year service warranty, subject to its agreed scope and terms.', cards:[{title:'At handover',copy:'Testing, client walkthrough, care guidance and warranty record.'},{title:'If something goes wrong',copy:'Send the project reference, photos and a clear description through WhatsApp.'},{title:'Our response',copy:'We assess coverage, arrange inspection when necessary and document the resolution.'}] },
  { slug:'team', eyebrow:'The people responsible', title:'A permanent core. Verified specialists.', lead:'Every project has clear ownership from client communication through procurement, site quality and handover.', cards:[{title:'Design & Client Experience',copy:'Guides the brief, design selection and approvals.'},{title:'Project Manager',copy:'Coordinates procurement, programme and specialist teams.'},{title:'Quality Supervisor',copy:'Checks critical construction stages before work proceeds.'},{title:'TILERSHUB Verified Specialists',copy:'Trade teams selected for the needs and location of each project.'}] },
  { slug:'faq', eyebrow:'Questions, answered honestly', title:'Before design. Before construction.', lead:'Clear answers help clients make better decisions and help projects start correctly.', cards:[{title:'Can I buy a design without construction?',copy:'Ask our team about the design-file option available for your location and space.'},{title:'Are starting prices fixed?',copy:'No. They are catalogue entry points. The project quotation becomes fixed after site inspection and customisation.'},{title:'Can I change fixtures and colours?',copy:'Yes, while protecting technical performance, design consistency and budget clarity.'},{title:'Do you work outside Colombo?',copy:'Yes, subject to location, scope and site assessment.'},{title:'How long does a renovation take?',copy:'A typical bathroom programme is around six weeks; other spaces depend on scope and procurement.'}] },
  { slug:'terms', eyebrow:'Legal', title:'Terms & conditions.', lead:'The terms governing quotations, approvals, variations, construction and handover.', cards:[{title:'Quotations',copy:'Validity, scope, assumptions, exclusions and changes must be documented.'},{title:'Client responsibilities',copy:'Access, approvals, utilities, timely decisions and agreed payments.'},{title:'Variations',copy:'Additional or changed work requires written approval and may affect cost and time.'},{title:'Handover',copy:'Completion, defects review, care instructions and warranty commencement.'}] },
  { slug:'privacy', eyebrow:'Legal', title:'Privacy policy.', lead:'How inquiry, booking, analytics and communication data is collected and used.', cards:[{title:'Information collected',copy:'Contact details, property location, project information, submitted photos and site usage data.'},{title:'How it is used',copy:'Responding to inquiries, preparing services, improving the website and maintaining project records.'},{title:'Sharing and retention',copy:'Data is shared only with necessary service providers or where legally required.'},{title:'Contact',copy:'Contact LUXEhome to request access, correction or deletion.'}] },
  { slug:'warranty-terms', eyebrow:'Legal', title:'Warranty terms.', lead:'The documented conditions of LUXEhome’s one-year service warranty.', cards:[{title:'Covered work',copy:'Eligible workmanship defects within the agreed construction scope.'},{title:'Not covered',copy:'Misuse, third-party alteration, normal wear and matters outside the agreed scope.'},{title:'Reporting',copy:'Provide the project reference, evidence and reasonable access for assessment.'}] },
  { slug:'payment-cancellation', eyebrow:'Legal', title:'Payments & cancellation.', lead:'Clear payment stages protect the client, procurement and construction programme.', cards:[{title:'Payment stages',copy:'Deposits and progress payments follow the approved quotation and programme.'},{title:'Procurement',copy:'Custom and ordered items may become non-refundable once approved and purchased.'},{title:'Cancellation',copy:'Any cancellation is assessed against completed work, commitments and documented costs.'}] },
];
