export interface PublicInfoPage {
  slug: string; eyebrow: string; title: string; lead: string;
  cards: Array<{ title: string; copy: string }>;
}

/** Shared answers for the high-intent project initiation stage. These are
    rendered on both the booking page and the main FAQ page so the website and
    sales team can use one consistent explanation. */
export const PROJECT_INITIATION_FAQ: Array<{ title: string; copy: string }> = [
  {
    title: 'Why can’t I receive a final quotation first?',
    copy: 'A dependable final quotation requires the actual measurements, site conditions, service changes, detailed design, material selection and fixture scope. Before initiation, we can share published starting prices or a likely budget range. The final construction quotation is prepared only after the site visit and design, so we do not give you one price and change it later.',
  },
  {
    title: 'Exactly what does LKR 50,000 include?',
    copy: 'For one bathroom, it includes the site consultation, measurements and technical review, detailed design with five presentation images, material and finish selection, a 3D walkthrough video link, project timeline, quality commitments, applicable warranties and the final construction quotation in one proposal PDF.',
  },
  {
    title: 'Is the LKR 50,000 an additional cost?',
    copy: 'Not when LUXEhome constructs that bathroom. It becomes your first project payment and is credited in full against the construction balance. For example, if the agreed contract value is LKR 1,500,000, the remaining balance is LKR 1,450,000 after the LKR 50,000 already paid.',
  },
  {
    title: 'When will I receive the proposal?',
    copy: 'The complete proposal is delivered within seven working days after the site visit. The delivery period begins after the visit because the design and final quotation must be based on the measured room and confirmed site conditions.',
  },
  {
    title: 'What happens if I do not proceed?',
    copy: 'You still receive the completed proposal. The LKR 50,000 is retained to cover the professional site consultation, measurements, design, material selection, costing and proposal work already completed.',
  },
  {
    title: 'What happens if I have several bathrooms?',
    copy: 'Start with one bathroom for LKR 50,000 and review its complete proposal first. If you then appoint LUXEhome for the wider construction project, the remaining bathrooms can be developed under that agreement. If you want separate detailed proposals for additional bathrooms before appointing construction, each additional proposal requires its own LKR 50,000 initiation payment, credited to its related construction contract.',
  },
  {
    title: 'How much does a typical bathroom cost?',
    copy: 'A complete LUXEhome bathroom typically starts around LKR 1.5 million. The actual amount depends on room size, whether it is new construction or renovation, existing site conditions, service changes, materials, fixtures and the selected design. Published design prices are starting guides; the proposal contains the final construction quotation.',
  },
  {
    title: 'How are quality and warranties protected?',
    copy: 'The proposal records the approved materials, brands, scope, construction process, quality commitments and applicable warranty periods. During construction, critical stages such as plumbing pressure testing, waterproofing, flood testing, tile installation and final inspection are checked before handover. The applicable warranty record is issued with the completed project.',
  },
];

export const PUBLIC_INFO_PAGES: PublicInfoPage[] = [
  { slug:'how-it-works', eyebrow:'From first request to final clean', title:'Six stages. One responsible team.', lead:'Every stage is documented, approved and communicated before the next begins.', cards:[{title:'01 · Project request',copy:'Share your name, WhatsApp number, property location and the first bathroom you want us to develop. Dimensions are optional.'},{title:'02 · Initiation & site visit',copy:'We confirm the appointment and collect the LKR 50,000 project initiation deposit for one bathroom. On site, we measure the room and assess existing conditions.'},{title:'03 · Detailed design',copy:'We develop the bathroom around the measured room, including five presentation images, a 3D walkthrough and the agreed material direction.'},{title:'04 · Complete proposal',copy:'Within seven working days after the site visit, you receive one PDF with the design visuals, material selection, timeline, quality commitments, warranties and final construction quotation.'},{title:'05 · Construction',copy:'If you appoint LUXEhome to build, the full LKR 50,000 is shown as an advance and deducted from the construction balance. Verified teams build while progress and quality checks are shared through WhatsApp.'},{title:'06 · Clean & handover',copy:'We test, inspect, clean and hand over the completed space with its warranty record.'}] },
  { slug:'bathroom-renovation', eyebrow:'Bathrooms', title:'Bathroom design & renovation.', lead:'A complete room—designed, documented and built from waterproofing to final fixture.', cards:[{title:'Choose a named design',copy:'Start with a documented Flora, Island, Heritage or Ceylon Gems bathroom.'},{title:'Customised for the room',copy:'Layouts, drawings, finishes and fixtures are adapted to the actual site.'},{title:'One accountable team',copy:'Civil, plumbing, electrical, tiling, ceiling and finishing are coordinated together.'}] },
  { slug:'materials-brands', eyebrow:'Materials & brands', title:'Known products. Written specifications.', lead:'We specify brands and construction systems openly so clients know what is going into their home.', cards:[{title:'Waterproofing',copy:'Tokyo Super 2K waterproofing with the preparation, application and testing method documented.'},{title:'Tile installation',copy:'Swisstek adhesive and grout selected for the tile, substrate and room condition.'},{title:'Plumbing',copy:'S-lon pipes and accessories with supply, waste and drainage routes documented.'},{title:'Electrical',copy:'ACL wiring and cables with points, circuits and switching resolved before finishes.'},{title:'Finishes',copy:'Swiss Bathware, Rocell, iPanel, tempered glass, Eco Board and 5mm mirrors—with alternatives approved before purchase.'}] },
  { slug:'pricing-guide', eyebrow:'Pricing clarity', title:'A starting point—not a hidden promise.', lead:'Published design prices are honest starting points. The final project price follows the site visit, detailed design and material selection.', cards:[{title:'Sigiriya · minimum 4.5 m²',copy:'A new bathroom starts from LKR 1.775M. Renovating an existing bathroom starts from LKR 1.884M.'},{title:'Choose by room size',copy:'Compare Minimum, Recommended and Spacious fits. Larger or technically complex rooms receive a custom price.'},{title:'What stays clear',copy:'The approved scope, quantities, materials, fixtures, labour, programme, payment stages and exclusions are written into the quotation.'}] },
  { slug:'warranty-aftercare', eyebrow:'Warranty & aftercare', title:'Our responsibility continues after handover.', lead:'Warranty is given against each part of the work, not as one blanket period, and is recorded with your project at handover — subject to the agreed scope and terms.', cards:[{title:'Warranty by task',copy:'Bathware 15 years · Waterproofing 10 years · Plumbing 10 years · Wiring 10 years · Taps & showers 5 years · Ceiling 5 years · Light fixtures 1 year · Tempered glass 1 year.'},{title:'At handover',copy:'Testing, client walkthrough, care guidance and the written warranty record.'},{title:'If something goes wrong',copy:'Send the project reference, photos and a clear description through WhatsApp.'},{title:'Our response',copy:'We assess coverage, arrange inspection when necessary and document the resolution.'}] },
  { slug:'team', eyebrow:'The people responsible', title:'A permanent core. Verified specialists.', lead:'Every project has clear ownership from client communication through procurement, site quality and handover.', cards:[{title:'Design & Client Experience',copy:'Guides the brief, design selection and approvals.'},{title:'Project Manager',copy:'Coordinates procurement, programme and specialist teams.'},{title:'Quality Supervisor',copy:'Checks critical construction stages before work proceeds.'},{title:'TILERSHUB Verified Specialists',copy:'Trade teams selected for the needs and location of each project.'}] },
  { slug:'faq', eyebrow:'Questions, answered honestly', title:'Before design. Before construction.', lead:'Clear answers help clients make better decisions and help projects start correctly.', cards:[...PROJECT_INITIATION_FAQ,{title:'Do I need to know my bathroom size?',copy:'No. Choose “please measure it” when starting the project. Approximate dimensions are helpful but never required.'},{title:'Can I change fixtures and colours?',copy:'Yes, while protecting technical performance, design consistency and budget clarity.'},{title:'Do you work outside Colombo?',copy:'Yes, subject to location, scope and site assessment.'},{title:'How long does a renovation take?',copy:'A typical bathroom programme is around six weeks; the actual programme depends on site condition, scope and procurement.'}] },
  { slug:'terms', eyebrow:'Legal', title:'Terms & conditions.', lead:'The terms governing quotations, approvals, variations, construction and handover.', cards:[{title:'Quotations',copy:'Validity, scope, assumptions, exclusions and changes must be documented.'},{title:'Client responsibilities',copy:'Access, approvals, utilities, timely decisions and agreed payments.'},{title:'Variations',copy:'Additional or changed work requires written approval and may affect cost and time.'},{title:'Handover',copy:'Completion, defects review, care instructions and warranty commencement.'}] },
  { slug:'privacy', eyebrow:'Legal', title:'Privacy policy.', lead:'How inquiry, booking, analytics and communication data is collected and used.', cards:[{title:'Information collected',copy:'Contact details, property location, project information, submitted photos and site usage data.'},{title:'How it is used',copy:'Responding to inquiries, preparing services, improving the website and maintaining project records.'},{title:'Sharing and retention',copy:'Data is shared only with necessary service providers or where legally required.'},{title:'Contact',copy:'Contact LUXEhome to request access, correction or deletion.'}] },
  { slug:'warranty-terms', eyebrow:'Legal', title:'Warranty terms.', lead:'The documented conditions of the warranty periods LUXEhome gives against each part of the work.', cards:[{title:'Cover periods',copy:'Each task carries its own period from handover, as recorded in the project warranty schedule.'},{title:'Covered work',copy:'Eligible workmanship defects within the agreed construction scope.'},{title:'Warranty by task',copy:'Bathware, waterproofing, plumbing, wiring, tapware, showers, ceiling, light fixtures and tempered glass each carry the period stated in the project warranty record.'},{title:'Not covered',copy:'Misuse, third-party alteration, normal wear and matters outside the agreed scope.'},{title:'Reporting',copy:'Provide the project reference, evidence and reasonable access for assessment.'}] },
  { slug:'payment-cancellation', eyebrow:'Legal', title:'Payment & cancellation policy.', lead:'Clear payment stages protect the client, design work, procurement and construction programme.', cards:[{title:'Project initiation · LKR 50,000 per bathroom',copy:'Payment is requested only after the service area and site appointment are confirmed. It covers the consultation, measurements, detailed design and complete proposal for one bathroom.'},{title:'Proposal delivery',copy:'The complete proposal is delivered within seven working days after the site visit and includes five design images, material selection, timeline, quality commitments, applicable warranties and the final construction quotation, plus a 3D walkthrough video link.'},{title:'Credited to construction',copy:'If LUXEhome is appointed to construct that bathroom, 100% of the LKR 50,000 is recorded as an advance and deducted from the remaining construction balance. It does not reduce the agreed contract value.'},{title:'If construction does not proceed',copy:'The initiation deposit is retained to cover the consultation, design and proposal work already completed.'},{title:'Multiple bathrooms',copy:'Each bathroom proposal requires its own LKR 50,000 initiation deposit. A client may start with one bathroom and review that proposal before initiating any others.'},{title:'Cancellation or delay',copy:'Cancellation, delayed approvals or payments are assessed against completed work, commitments and documented costs, and may move project dates.'}] },
];
