export interface PublicInfoPage {
  slug: string; eyebrow: string; title: string; lead: string;
  cards: Array<{ title: string; copy: string }>;
}

export const PUBLIC_INFO_PAGES: PublicInfoPage[] = [
  { slug:'how-it-works', eyebrow:'From first request to final clean', title:'Six stages. One responsible team.', lead:'Every stage is documented, approved and communicated before the next begins.', cards:[{title:'01 · Inspection request',copy:'Share your name, WhatsApp number and property location. Bathroom dimensions are optional.'},{title:'02 · Confirmed site inspection',copy:'We confirm the appointment, collect the LKR 10,000 inspection fee, measure the room and assess existing conditions.'},{title:'03 · Design & approval',copy:'The suitable named design is selected and its layout, finishes, fixtures and documents are adapted to the actual room.'},{title:'04 · Final quotation',copy:'You receive a documented scope, programme, payment stages and final quotation. The 10% construction confirmation comes only after approval.'},{title:'05 · Construction',copy:'Verified teams build while progress, decisions and quality checks are shared through WhatsApp.'},{title:'06 · Clean & handover',copy:'We test, inspect, clean and hand over the completed space with its warranty record.'}] },
  { slug:'bathroom-renovation', eyebrow:'Bathrooms', title:'Bathroom design & renovation.', lead:'A complete room—designed, documented and built from waterproofing to final fixture.', cards:[{title:'Choose a named design',copy:'Start with a documented Flora, Island, Heritage or Ceylon Gems bathroom.'},{title:'Customised for the room',copy:'Layouts, drawings, finishes and fixtures are adapted to the actual site.'},{title:'One accountable team',copy:'Civil, plumbing, electrical, tiling, ceiling and finishing are coordinated together.'}] },
  { slug:'materials-brands', eyebrow:'Materials & brands', title:'Known products. Written specifications.', lead:'We specify brands and construction systems openly so clients know what is going into their home.', cards:[{title:'Waterproofing',copy:'Tokyo Super 2K waterproofing with the preparation, application and testing method documented.'},{title:'Tile installation',copy:'Swisstek adhesive and grout selected for the tile, substrate and room condition.'},{title:'Plumbing',copy:'S-lon pipes and accessories with supply, waste and drainage routes documented.'},{title:'Electrical',copy:'ACL wiring and cables with points, circuits and switching resolved before finishes.'},{title:'Finishes',copy:'Swiss Bathware, Rocell, iPanel, tempered glass, Eco Board and 5mm mirrors—with alternatives approved before purchase.'}] },
  { slug:'pricing-guide', eyebrow:'Pricing clarity', title:'A starting point—not a hidden promise.', lead:'Published design prices are honest starting points. The fixed project price follows inspection and customisation.', cards:[{title:'Sigiriya · minimum 5 m²',copy:'A new bathroom starts from LKR 2.060M. Renovating an existing bathroom starts from LKR 2.175M.'},{title:'Choose by room size',copy:'Compare Minimum, Recommended and Spacious fits. Larger or technically complex rooms receive a custom price.'},{title:'What stays clear',copy:'The approved scope, quantities, materials, fixtures, labour, programme, payment stages and exclusions are written into the quotation.'}] },
  { slug:'warranty-aftercare', eyebrow:'Warranty & aftercare', title:'Our responsibility continues after handover.', lead:'Warranty is given against each part of the work, not as one blanket period, and is recorded with your project at handover — subject to the agreed scope and terms.', cards:[{title:'Warranty by task',copy:'Bathware 15 years · Waterproofing 10 years · Plumbing 10 years · Wiring 10 years · Taps & showers 5 years · Ceiling 5 years · Light fixtures 1 year · Tempered glass 1 year.'},{title:'At handover',copy:'Testing, client walkthrough, care guidance and the written warranty record.'},{title:'If something goes wrong',copy:'Send the project reference, photos and a clear description through WhatsApp.'},{title:'Our response',copy:'We assess coverage, arrange inspection when necessary and document the resolution.'}] },
  { slug:'team', eyebrow:'The people responsible', title:'A permanent core. Verified specialists.', lead:'Every project has clear ownership from client communication through procurement, site quality and handover.', cards:[{title:'Design & Client Experience',copy:'Guides the brief, design selection and approvals.'},{title:'Project Manager',copy:'Coordinates procurement, programme and specialist teams.'},{title:'Quality Supervisor',copy:'Checks critical construction stages before work proceeds.'},{title:'TILERSHUB Verified Specialists',copy:'Trade teams selected for the needs and location of each project.'}] },
  { slug:'faq', eyebrow:'Questions, answered honestly', title:'Before design. Before construction.', lead:'Clear answers help clients make better decisions and help projects start correctly.', cards:[{title:'Do I need to know my bathroom size?',copy:'No. Choose “please measure it” when requesting the site inspection. Approximate dimensions are helpful but never required.'},{title:'What does the site inspection cost?',copy:'LKR 10,000. We confirm the location, appointment and payment details before asking you to pay.'},{title:'Can I continue with design only?',copy:'Yes. After inspection, the LKR 50,000 adaptation path can include an adapted layout, 3D concept, one revision, finish direction and preliminary pricing. The LKR 10,000 inspection fee is credited.'},{title:'When is the 10% construction payment due?',copy:'Only after inspection, design adaptation, scope confirmation and your approval of the final quotation—not when the first request is sent.'},{title:'Are starting prices fixed?',copy:'No. They are catalogue entry points. The project quotation becomes fixed after site inspection and customisation.'},{title:'Can I change fixtures and colours?',copy:'Yes, while protecting technical performance, design consistency and budget clarity.'},{title:'Do you work outside Colombo?',copy:'Yes, subject to location, scope and site assessment.'},{title:'How long does a renovation take?',copy:'A typical bathroom programme is around six weeks; the actual programme depends on site condition, scope and procurement.'}] },
  { slug:'terms', eyebrow:'Legal', title:'Terms & conditions.', lead:'The terms governing quotations, approvals, variations, construction and handover.', cards:[{title:'Quotations',copy:'Validity, scope, assumptions, exclusions and changes must be documented.'},{title:'Client responsibilities',copy:'Access, approvals, utilities, timely decisions and agreed payments.'},{title:'Variations',copy:'Additional or changed work requires written approval and may affect cost and time.'},{title:'Handover',copy:'Completion, defects review, care instructions and warranty commencement.'}] },
  { slug:'privacy', eyebrow:'Legal', title:'Privacy policy.', lead:'How inquiry, booking, analytics and communication data is collected and used.', cards:[{title:'Information collected',copy:'Contact details, property location, project information, submitted photos and site usage data.'},{title:'How it is used',copy:'Responding to inquiries, preparing services, improving the website and maintaining project records.'},{title:'Sharing and retention',copy:'Data is shared only with necessary service providers or where legally required.'},{title:'Contact',copy:'Contact LUXEhome to request access, correction or deletion.'}] },
  { slug:'warranty-terms', eyebrow:'Legal', title:'Warranty terms.', lead:'The documented conditions of the warranty periods LUXEhome gives against each part of the work.', cards:[{title:'Cover periods',copy:'Each task carries its own period from handover, as recorded in the project warranty schedule.'},{title:'Covered work',copy:'Eligible workmanship defects within the agreed construction scope.'},{title:'Warranty by task',copy:'Bathware, waterproofing, plumbing, wiring, tapware, showers, ceiling, light fixtures and tempered glass each carry the period stated in the project warranty record.'},{title:'Not covered',copy:'Misuse, third-party alteration, normal wear and matters outside the agreed scope.'},{title:'Reporting',copy:'Provide the project reference, evidence and reasonable access for assessment.'}] },
  { slug:'payment-cancellation', eyebrow:'Legal', title:'Payment & cancellation policy.', lead:'Clear payment stages protect the client, procurement and construction programme.', cards:[{title:'Site inspection · LKR 10,000',copy:'The inspection fee covers the confirmed professional site visit. Payment is requested only after the location and appointment are agreed.'},{title:'Design adaptation · LKR 50,000',copy:'Where selected, the inspection fee is credited and the remaining LKR 40,000 covers the stated adaptation deliverables. Full technical construction documents require a separate agreed scope.'},{title:'Construction confirmation',copy:'The 10% construction payment is requested only after inspection, design and scope confirmation, and approval of the final quotation.'},{title:'Cancellation',copy:'Any cancellation is assessed against completed work, custom orders, commitments and documented costs.'},{title:'Late decisions or payments',copy:'Delayed approvals or payments can move procurement and construction dates; changes are communicated and documented.'}] },
];
